openapi: 3.0.3
info:
  title: AppSec Guide API
  version: 0.0.1
  description: |
    API to help developers prioritize which security issues to fix first.
    
    The project automatically identifies the user and available resources using OIDC and fetches available metadata
    from a wide range of sources. We then use this data to calculate a risk score for each vulnerability and return 
    a prioritized list to the user.
  contact:
    name: NAV Security Team
    email: security@nav.no

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://appsec-guide.nav.cloud.nais.io
    description: Production server

tags:
  - name: Health
    description: Health check endpoints
  - name: Vulnerabilities
    description: Vulnerability management and prioritization

security:
  - bearerAuth: []

paths:
  /isalive:
    get:
      tags:
        - Health
      summary: Liveness probe
      description: Returns a simple text response indicating the service is alive
      operationId: isAlive
      security: []
      responses:
        '200':
          description: Service is alive
          content:
            text/plain:
              schema:
                type: string
                example: A-OK

  /isready:
    get:
      tags:
        - Health
      summary: Readiness probe
      description: Returns a simple text response indicating the service is ready to accept traffic
      operationId: isReady
      security: []
      responses:
        '200':
          description: Service is ready
          content:
            text/plain:
              schema:
                type: string
                example: KIROV REPORTING

  /vulnerabilities/user:
    get:
      tags:
        - Vulnerabilities
      summary: Get vulnerabilities for authenticated user
      description: |
        Fetches all vulnerabilities for teams the authenticated user belongs to.
        The response includes vulnerability details, workload information, ingress types, 
        and whether the vulnerability is in the CISA KEV catalog.
      operationId: getVulnerabilitiesForUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved vulnerabilities
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnResponse'
              examples:
                withVulnerabilities:
                  summary: Response with vulnerabilities
                  value:
                    teams:
                      - team: team-alpha
                        workloads:
                          - name: app1
                            ingressTypes:
                              - internal
                              - external
                            vulnerabilities:
                              - identifier: CVE-2023-12345
                                severity: HIGH
                                suppressed: false
                                hasKevEntry: true
                              - identifier: CVE-2023-54321
                                severity: MEDIUM
                                suppressed: true
                                hasKevEntry: false
                emptyResponse:
                  summary: Response with no vulnerabilities
                  value:
                    teams: []
        '400':
          description: Bad request - missing or invalid claims in token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
              example:
                type: about:blank
                title: Bad Request
                status: 400
                detail: preferred_username claim not found in token
                instance: /vulnerabilities/user
        '401':
          description: Unauthorized - missing or invalid authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
              example:
                type: about:blank
                title: Unauthorized
                status: 401
                detail: Authentication required
                instance: /vulnerabilities/user
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
              example:
                type: about:blank
                title: Internal Server Error
                status: 500
                detail: "Failed to fetch vulnerabilities: Connection timeout"
                instance: /vulnerabilities/user

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token obtained from Entra ID. The token must contain:
        - NAVident claim for user identification
        - preferred_username claim for email/username

  schemas:
    VulnResponse:
      type: object
      required:
        - teams
      properties:
        teams:
          type: array
          description: List of teams with their associated vulnerabilities
          items:
            $ref: '#/components/schemas/VulnTeamDto'
      example:
        teams:
          - team: team-alpha
            workloads:
              - name: app1
                ingressTypes:
                  - internal
                  - external
                vulnerabilities:
                  - identifier: CVE-2023-12345
                    severity: HIGH
                    suppressed: false
                    hasKevEntry: true

    VulnTeamDto:
      type: object
      required:
        - team
        - workloads
      properties:
        team:
          type: string
          description: Team slug identifier
          example: team-alpha
        workloads:
          type: array
          description: List of workloads belonging to this team
          items:
            $ref: '#/components/schemas/VulnWorkloadDto'

    VulnWorkloadDto:
      type: object
      required:
        - name
        - ingressTypes
        - vulnerabilities
      properties:
        name:
          type: string
          description: Workload/application name
          example: my-application
        ingressTypes:
          type: array
          description: Types of ingress configured for this workload
          items:
            type: string
            enum:
              - internal
              - external
              - loadbalancer
          example:
            - internal
            - external
        vulnerabilities:
          type: array
          description: List of vulnerabilities detected in this workload
          items:
            $ref: '#/components/schemas/VulnVulnerabilityDto'

    VulnVulnerabilityDto:
      type: object
      required:
        - identifier
        - severity
        - suppressed
        - hasKevEntry
      properties:
        identifier:
          type: string
          description: CVE identifier for the vulnerability
          pattern: '^CVE-\d{4}-\d+$'
          example: CVE-2023-12345
        severity:
          type: string
          description: Severity level of the vulnerability
          enum:
            - CRITICAL
            - HIGH
            - MEDIUM
            - LOW
            - UNKNOWN
          example: HIGH
        suppressed:
          type: boolean
          description: Whether this vulnerability has been suppressed by the team
          example: false
        hasKevEntry:
          type: boolean
          description: Whether this vulnerability is listed in the CISA Known Exploited Vulnerabilities (KEV) catalog
          example: true

    ProblemDetail:
      type: object
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          description: |
            A URI reference that identifies the problem type. 
            When dereferenced, it should provide human-readable documentation.
          example: about:blank
        title:
          type: string
          description: A short, human-readable summary of the problem type
          example: Bad Request
        status:
          type: integer
          description: The HTTP status code
          minimum: 100
          maximum: 599
          example: 400
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
          example: preferred_username claim not found in token
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem
          example: /vulnerabilities/user
      description: |
        RFC 9457 Problem Details for HTTP APIs.
        Used for all error responses to provide consistent error information.

